# based on https://github.com/arduino-libraries/ArduinoBLE/blob/master/.github/workflows/compile-examples.yml
name: Build for SAMD

# set workflow trigger
on:

  # Trigger workflow on every push and pull request
  push:
  pull_request:


# configure workflow jobs
jobs:

  # Build for SAMD
  build-for-samd:
    
    # setup OS
    runs-on: ubuntu-latest

    # setup environment
    env:
      SKETCHES_REPORTS_PATH: sketches-reports
    
    # test strategy & tested boards
    strategy:
      fail-fast: false
      matrix:
        board:
          - fqbn: arduino:sam:arduino_due_x_dbg       # Arduino Due (Programming Port)
            artifact-name-suffix: arduino_sam_arduino_due_x_dbg

    # integration test steps
    steps:

      # check-out this repository
      - uses: actions/checkout@v4.2.2

      # Install Arduino CLI
      - name: install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          export PATH="$PWD/bin:$PATH"
          echo "PATH=$PATH"
          which arduino-cli
          arduino-cli version

      # Install required boards & libraries
      - name: install ESP8266 core
        run: |
          export PATH="$PWD/bin:$PATH"
          arduino-cli core update-index
          arduino-cli core install arduino:sam

      # build Arduino examples
      - name: Compile sketches
        run: |
          arduino-cli compile --fqbn arduino:sam:arduino_due_x_dbg --build-property build.extra_flags="-DLIN_MASTER_DEBUG_SERIAL=Serial -DLIN_MASTER_DEBUG_LEVEL=3" examples/LIN_master_HWSerial_Blk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
