# based on https://github.com/arduino-libraries/ArduinoBLE/blob/master/.github/workflows/compile-examples.yml
name: Build for SAMD

# set workflow trigger
on:

  # Trigger workflow on every push and pull request
  push:
  pull_request:


# configure workflow jobs
jobs:

  # Build for SAMD
  build-for-samd:
    
    # setup OS
    runs-on: ubuntu-latest

    # setup environment
    env:
      SKETCHES_REPORTS_PATH: sketches-reports
    
    # test strategy & tested boards
    strategy:
      fail-fast: false
      matrix:
        board:
          - fqbn: arduino:sam:arduino_due_x_dbg       # Arduino Due (Programming Port)
            artifact-name-suffix: arduino_sam_arduino_due_x_dbg

    # integration test steps
    steps:

      # check-out this repository
      - uses: actions/checkout@v4.2.2

      # Install Arduino CLI
      - name: install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          export PATH="$PWD/bin:$PATH"
          echo "PATH=$PATH"
          which arduino-cli
          arduino-cli version

      # Create Board Manager file
      - name: create arduino-cli.yaml
        run: |
          mkdir -p ~/.arduino15
          echo "directory: ~/.arduino15" > ~/.arduino15/arduino-cli.yaml
          echo "board_manager:" >> ~/.arduino15/arduino-cli.yaml
          echo "  additional_urls:" >> ~/.arduino15/arduino-cli.yaml
          echo "    - https://adafruit.github.io/arduino-board-index/package_adafruit_index.json" >> ~/.arduino15/arduino-cli.yaml
          echo "    - https://arduino.esp8266.com/stable/package_esp8266com_index.json" >> ~/.arduino15/arduino-cli.yaml
          echo "    - https://espressif.github.io/arduino-esp32/package_esp32_index.json" >> ~/.arduino15/arduino-cli.yaml
          cat ~/.arduino15/arduino-cli.yaml
      
      # Install required boards & libraries
      - name: install SAMD core
        run: |
          export PATH="$PWD/bin:$PATH"
          arduino-cli core update-index
          arduino-cli core install arduino:sam

      # build Arduino examples
      - name: Compile sketches
        run: |
          export PATH="$PWD/bin:$PATH"
          arduino-cli compile --fqbn arduino:sam:arduino_due_x_dbg --build-property build.extra_flags="-DLIN_MASTER_DEBUG_SERIAL=Serial -DLIN_MASTER_DEBUG_LEVEL=3" --libraries . examples/LIN_master_HWSerial_Blk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
