# based on https://github.com/arduino-libraries/ArduinoBLE/blob/master/.github/workflows/compile-examples.yml
name: Build Lib Examples

on:

  # Trigger workflow on every push and pull request
  push:
  pull_request:
  
  # Also run every 7 days to catch breakage caused by changes to external resources (libraries, platforms).
  schedule:
    # Minute, Hour, Day of Month, Month, Day of Week -> every 7 days at 9.20pm (UTC)
    - cron: '20 21 */7 * *'

jobs:

  # Build for ESP8266
  build-for-esp8266:
    runs-on: ubuntu-latest
    env:
      SKETCHES_REPORTS_PATH: sketches-reports
    strategy:
      fail-fast: false
      matrix:
        board:
          - fqbn: esp8266:esp8266:d1_mini_clone       # ESP8255 Wemos D1 Mini (clone)
            artifact-name-suffix: d1_mini_clone
    steps:

      # Install Arduino CLI
      - name: install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          export PATH="$PWD/bin:$PATH"
          echo "PATH=$PATH"
          which arduino-cli
          arduino-cli version

      # Create Board Manager file
      - name: create arduino-cli.yaml
        run: |
          mkdir -p ~/.arduino15
          echo "directory: ~/.arduino15" > ~/.arduino15/arduino-cli.yaml
          echo "board_manager:" >> ~/.arduino15/arduino-cli.yaml
          echo "  additional_urls:" >> ~/.arduino15/arduino-cli.yaml
          echo "    - https://adafruit.github.io/arduino-board-index/package_adafruit_index.json" >> ~/.arduino15/arduino-cli.yaml
          echo "    - https://arduino.esp8266.com/stable/package_esp8266com_index.json" >> ~/.arduino15/arduino-cli.yaml
          echo "    - https://espressif.github.io/arduino-esp32/package_esp32_index.json" >> ~/.arduino15/arduino-cli.yaml
          cat ~/.arduino15/arduino-cli.yaml
      
      # Install required boards
      - name: install ESP8266 core
        run: |
          export PATH="$PWD/bin:$PATH"
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266

      # check-out this repository
      - uses: actions/checkout@v4.2.2

      # build Arduino examples
      - uses: arduino/compile-sketches@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}   # required for private repos
          fqbn: ${{ matrix.board.fqbn }}
          libraries: |
            - source-path: ./
          sketch-paths: |
            - examples/LIN_master_HWSerial_ESP8266_Blk
            - examples/LIN_master_SWSerial_Blk
            - examples/LIN_master_HWSerial_ESP8266_Bkg
            - examples/LIN_master_HWSerial_ESP8266_Bkg_Evt
            - examples/LIN_master_HWSerial_ESP8266_Ticker
          cli-compile-flags: |
            - --build-property "compiler.cpp.extra_flags=-Wall -Wextra -Werror"
            
      # upload test reports
      - uses: actions/upload-artifact@v4.4.3
        with:
          if-no-files-found: error
          path: ${{ env.SKETCHES_REPORTS_PATH }}
          name: sketches-report-${{ matrix.board.artifact-name-suffix }}
