# based on https://github.com/arduino-libraries/ArduinoBLE/blob/master/.github/workflows/compile-examples.yml
name: Build Lib Examples

on:

  # Trigger workflow on every push and pull request
  push:
  pull_request:
  
  # Also run every 7 days to catch breakage caused by changes to external resources (libraries, platforms).
  schedule:
    # Minute, Hour, Day of Month, Month, Day of Week -> every 7 days at 9.20pm (UTC)
    - cron: '20 21 */7 * *'

jobs:

  # Build for ESP8266
  build-for-esp8266:
    runs-on: ubuntu-latest
    env:
      SKETCHES_REPORTS_PATH: sketches-reports
    strategy:
      fail-fast: false
      matrix:
        board:
          - fqbn: esp8266:esp8266:d1_mini_clone       # ESP8255 Wemos D1 Mini (clone)
            artifact-name-suffix: d1_mini_clone
    steps:
      - uses: actions/checkout@v4.2.2                 # check-out this repo
      - name: Install Arduino ESP8266
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "Adding Arduino CLI to PATH"
          export PATH="$PWD/bin:$PATH"
          echo "PATH=$PATH"
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266
      - uses: arduino/compile-sketches@v1.1.2         # build Arduino examples
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}   # required for private repos
          fqbn: ${{ matrix.board.fqbn }}
          libraries: |
            - source-path: ./
          sketch-paths: |
            - examples/LIN_master_HWSerial_ESP8266_Blk
            - examples/LIN_master_SWSerial_Blk
            - examples/LIN_master_HWSerial_ESP8266_Bkg
            - examples/LIN_master_HWSerial_ESP8266_Bkg_Evt
            - examples/LIN_master_HWSerial_ESP8266_Ticker
          cli-compile-flags: |
            - --warnings="all"
      - uses: actions/upload-artifact@v4.4.3          # upload test reports
        with:
          if-no-files-found: error
          path: ${{ env.SKETCHES_REPORTS_PATH }}
          name: sketches-report-${{ matrix.board.artifact-name-suffix }}
