# based on https://github.com/arduino-libraries/ArduinoBLE/blob/master/.github/workflows/compile-examples.yml
name: Build Lib Examples

# set workflow trigger
on:

  # Trigger workflow on every push and pull request
  push:
  pull_request:
  
  # Also run periodically to catch breakage caused by changes to external resources (libraries, platforms).
  schedule:
    # Minute, Hour, Day of Month, Month, Day of Week (UTC timezone)
    #- cron: '20 21 */7 * *'
    - cron: '0 1 2 * *'


# configure workflow jobs
jobs:

  # Build for AVR
  build-for-avr:
    
    # setup OS
    runs-on: ubuntu-latest

    # setup environment
    env:
      SKETCHES_REPORTS_PATH: sketches-reports
    
    # test strategy & tested boards
    strategy:
      fail-fast: false
      matrix:
        board:
          - fqbn: arduino:avr:mega                    # Arduino Mega2560
            artifact-name-suffix: arduino_avr_mega

    # integration test steps
    steps:

      # check-out this repository
      - uses: actions/checkout@v4.2.2

      # build Arduino examples
      - uses: arduino/compile-sketches@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}   # required for private repos
          fqbn: ${{ matrix.board.fqbn }}
          libraries: |
            - source-path: ./
          sketch-paths: |
            - examples/LIN_master_Dual_HWSerial_Bkg
            - examples/LIN_master_HWSerial_Bkg
            - examples/LIN_master_HWSerial_Bkg_Evt
            - examples/LIN_master_HWSerial_Blk
            - examples/LIN_master_RS485_HWSerial_Bkg
            - examples/LIN_master_RS485_HWSerial_Blk
            - examples/LIN_master_RS485_SWSerial_Blk
            - examples/LIN_master_SWSerial_Blk
          cli-compile-flags: |
            - --verbose
            - --build-property
            - build.extra_flags=-Wall -DLIN_MASTER_DEBUG_SERIAL=Serial -DLIN_MASTER_DEBUG_LEVEL=3

      # upload test reports
      - uses: actions/upload-artifact@v4.4.3
        with:
          if-no-files-found: error
          path: ${{ env.SKETCHES_REPORTS_PATH }}
          name: sketches-report-${{ matrix.board.artifact-name-suffix }}
